%Pyloc Configuration File
---
lead_types:
  D:
    name: Depth
    radius: 3
    spacing: 10
    max_y: 1
  G:
    name: Grid
    radius: 6
    spacing: 20
  S:
    name: Strip
    radius: 6
    spacing: 20

ct_threshold: 99.9

ct_max_color: 1
ct_min_color: .3
lead_max_color: 1
lead_min_color: .25


colormaps:
  ct: 'bone'
  selected: 'summer'
  default: 'spectral'

selection_iterations: 1

lead_display: >
  {lead.label}{contact.label} {contact.lead_location_str} {contact.center_str}

zero_index_lead: false
